### ISSUE TITLE
Hud part of the mod not working

### ISSUE THREAD

**Issue by HerrHenrimann** [Lightningtow/Hudify#3]
Hi, I was using your mod for the past 3 days or so now and today randomly it just stopped displaying the hud and the logs are displaying: [Spotify Thread/ERROR]:
(Hudify) exception caught in getPlaybackInfo(): Not a JSON Object: null
as an Error. Do you know a fix for that or if i can change something in the spotify settings to not make it cause that error? 
![{DC78FABA-818C-4E27-9A1E-EE165853055B}](https://github.com/user-attachments/assets/107760da-992e-422b-b96e-05d557c3f528)

**Comment by Lightningtow** [comment]
Huh, that shouldn't be happening. Is there any chance you could get me a link to the track you were listening to at the time? If you could get the whole Minecraft log with the 'print debug messages' setting enabled, that would also be very helpful

My best guess is that for whatever reason the track is missing some data that should be there, but I can't know for sure without more info

**Comment by HerrHenrimann** [comment]
Okay it has to do something with some song missing data, as you suggested, since I just started a different playlist and now its working. Now I'm just wondering why it broke since i did not click play on anything today until now. The issue persisted through relaunching and like resetting Spotify to where it doesn't have a Song shown at the bottom. I don't have a log to investigate since its fixed now but i will try to remember if it happens again. I'm guessing it just fully breaks when it comes across a song missing data.. I've tried playing the same songs that played after i was aware of the error and its working perfectly fine now. Anyways thanks for your help.

**Comment by Lightningtow** [comment]
If you remember which song you were listening to, the name of the track would still be helpful. Next update I'll make some changes so Hudify can handle missing data without crashing, but knowing which track it was could still help me identify if there were any problems beyond that

**Comment by HerrHenrimann** [comment]
I don't sorry. I only realized it after a while when the issue was already there. When it happened i clipped the last 10 minutes and for those it was already broken.

**Comment by Lightningtow** [comment]
Oh well. Thank you for the report!
